[metadata]
target_versions = ["1C536C3EF2E8BED348B38934B381E3DC427F3EBEE21FADDFBD7524FBB2388D77"]

# Native Mac translation of FullPartySelect.
#
# For convenience, the below addresses are 
# (1) the ghidra address in the 64 bit macos file ... (2) the raw offset.
# CSWGuiPartySelection::OnPanelAdded()				0x1002105fe ... 0x2115FE 
# Patched call site:                   				0x1002107fe ... 0x2117FE
# CSWGuiPartySelection::UpdateVisibleCharacters:	0x100210d1e ... 0x211D1E 
#
# This NOPs the same OnPanelAdded() call that the Windows GOG/Steam patch removes.
[[hooks]]
address = 0x2117FE
type = "simple"
original_bytes = [0xE8, 0x1b, 0x05, 0x00, 0x00]
replacement_bytes = [0x90, 0x90, 0x90, 0x90, 0x90]
