# Series of simple patches to avoid down-casting to a BYTE for placeable row IDs

[[hooks]]
address = 0x0057edc5
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8B, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x0057ede3
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x0057f0a2
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8B, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x0057f0c0
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x005850b9
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8B, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x005850d7
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x0058515a
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8B, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x00585178
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x0058527f
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x8e, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8b, 0x8e, 0x30, 0x02, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x00585a2f
type = "simple"
original_bytes    = [0x88, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x89, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x00586c05
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x8e, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8b, 0x8e, 0x30, 0x02, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x005871d8
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8B, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x005871f6
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x00587231
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8B, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x0058724f
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x0058728a
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8B, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x005872a8
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x005f67ab
type = "simple"
original_bytes    = [0x8a, 0x80, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x80, 0x0c, 0x01, 0x00, 0x00]

[[hooks]]
address = 0x005f67cb
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x005fdb1d
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x80, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x80, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x00607363
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x75, 0x0c]
replacement_bytes = [0x8b, 0x75, 0x0c, 0x90]

[[hooks]]
address = 0x006073f6
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x4d, 0x0c]
replacement_bytes = [0x8b, 0x4d, 0x0c, 0x90]

[[hooks]]
address = 0x00617823
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x80, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x80, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x00622ebc
type = "simple"
original_bytes    = [0x8a, 0x85, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x85, 0x0c, 0x01, 0x00, 0x00]

[[hooks]]
address = 0x00622ee4
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x00653add
type = "simple"
original_bytes    = [0x8a, 0x87, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x87, 0x0c, 0x01, 0x00, 0x00]

[[hooks]]
address = 0x00653afb
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x0068275c
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x8e, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x8e, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x006827f1
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x96, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x96, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x006829fa
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x8e, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x8e, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x00682a5a
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x8e, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x8e, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x00682aba
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x8e, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x8e, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x00682cd8
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x8e, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0x8e, 0x0c, 0x01, 0x00, 0x00, 0x90]

[[hooks]]
address = 0x00682f7e
type = "simple"
original_bytes    = [0x8a, 0x86, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8b, 0x86, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x00682f8d
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xc0]
replacement_bytes = [0x90, 0x90, 0x90]

[[hooks]]
address = 0x00683473
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xbe, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x8b, 0xbe, 0x0c, 0x01, 0x00, 0x00, 0x90]

# CSWCPlaceable::SetAppearance fix
[[hooks]]
address = 0x00682e39
type = "simple"
original_bytes    = [0x8a, 0x5c, 0x24, 0x28]
replacement_bytes = [0x8b, 0x5c, 0x24, 0x28]

[[hooks]]
address = 0x00682e4a
type = "simple"
original_bytes    = [0x88, 0x9e, 0x0c, 0x01, 0x00, 0x00]
replacement_bytes = [0x89, 0x9e, 0x0c, 0x01, 0x00, 0x00]

[[hooks]]
address = 0x00682e74
type = "simple"
original_bytes    = [0x0f, 0xb6, 0xfb]
replacement_bytes = [0x89, 0xdf, 0x90]

# CSWCMessage::HandleServerToPlayerPlaceableUpdate_Add fix
[[hooks]]
address = 0x0064d56c
type = "simple"
original_bytes    = [0xe8, 0xaf, 0x91, 0xe8, 0xff]
replacement_bytes = [0xe8, 0x0f, 0x92, 0xe8, 0xff]

[[hooks]]
address = 0x0064d571
type = "simple"
original_bytes    = [0x8a, 0xd8]
replacement_bytes = [0x89, 0xc3]

[[hooks]]
address = 0x0064d577
type = "simple"
original_bytes    = [0x88, 0x5c, 0x24, 0x28]
replacement_bytes = [0x89, 0x5c, 0x24, 0x28]

# CSWCArea::AddPlaceableObjectLight fix
[[hooks]]
address = 0x00606ed8
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x7d, 0x0c]
replacement_bytes = [0x8b, 0x7d, 0x0c, 0x90]

# CSWSPlaceable::LoadBodyBag fix
[[hooks]]
address = 0x00586515
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x4d, 0x08]
replacement_bytes = [0x8b, 0x4d, 0x08, 0x90]

[[hooks]]
address = 0x0058662b
type = "simple"
original_bytes    = [0x8a, 0x55, 0x08]
replacement_bytes = [0x8b, 0x55, 0x08]

[[hooks]]
address = 0x00586632
type = "simple"
original_bytes    = [0x88, 0x96, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x89, 0x96, 0x30, 0x02, 0x00, 0x00]

# There's a byte compare at 0x00586647 we may want to swap out

# CSWSObject::SpawnBodyBag fix
[[hooks]]
address = 0x004ce2e9
type = "simple"
original_bytes    = [0x88, 0x44, 0x24, 0x18]
replacement_bytes = [0x89, 0x44, 0x24, 0x18]

[[hooks]]
address = 0x004ce2ed
type = "simple"
original_bytes    = [0x0f, 0xb6, 0x85, 0xda, 0x09, 0x00, 0x00]
replacement_bytes = [0x8b, 0x85, 0xda, 0x09, 0x00, 0x00, 0x90]


# CSWSCreature::GetBodyBagAppearance fix
[[hooks]]
address = 0x004ef435
type = "simple"
original_bytes    = [0x8a, 0x44, 0x24, 0x08]
replacement_bytes = [0x8b, 0x44, 0x24, 0x08]


# CSWSArea::PackAreaIntoMessage fix
[[hooks]]
address = 0x0050b7ca
type = "simple"
original_bytes    = [0x8a, 0x85, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8b, 0x85, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x0050b7d0
type = "simple"
original_bytes    = [0x88, 0x44, 0x24, 0x18]
replacement_bytes = [0x89, 0x44, 0x24, 0x18]

[[hooks]]
address = 0x0050b7dd
type = "simple"
original_bytes    = [0xe8, 0xde, 0xaa, 0xfc, 0xff]
replacement_bytes = [0xe8, 0x9e, 0xaf, 0xfc, 0xff]

# CSWSMessage::AddPlaceableAppearanceToMessage fix
[[hooks]]
address = 0x00566e0e
type = "simple"
original_bytes    = [0x8a, 0x87, 0x30, 0x02, 0x00, 0x00]
replacement_bytes = [0x8b, 0x87, 0x30, 0x02, 0x00, 0x00]

[[hooks]]
address = 0x00566e16
type = "simple"
original_bytes    = [0x88, 0x44, 0x24, 0x28]
replacement_bytes = [0x89, 0x44, 0x24, 0x28]

[[hooks]]
address = 0x00566e23
type = "simple"
original_bytes    = [0xe8, 0x98, 0xf4, 0xf6, 0xff]
replacement_bytes = [0xe8, 0x58, 0xf9, 0xf6, 0xff]

# CSWCArea::LoadArea fix
[[hooks]]
address = 0x00608cfd
type = "simple"
original_bytes    = [0xe8, 0x1e, 0xda, 0xec, 0xff]
replacement_bytes = [0xe8, 0x7e, 0xda, 0xec, 0xff]

[[hooks]]
address = 0x00608d0b
type = "simple"
original_bytes    = [0x88, 0x44, 0x24, 0x28]
replacement_bytes = [0x89, 0x44, 0x24, 0x28]

[[hooks]]
address = 0x00608db1
type = "simple"
original_bytes    = [0xe8, 0x6a, 0xd9, 0xec, 0xff]
replacement_bytes = [0xe8, 0xca, 0xd9, 0xec, 0xff]

[[hooks]]
address = 0x00608dbf
type = "simple"
original_bytes    = [0x88, 0x44, 0x24, 0x28]
replacement_bytes = [0x89, 0x44, 0x24, 0x28]
