[patch]
id = "more-placeables-in-2da"
name = "[EXPERIMENTATL] Placeables 2DA Row Limit expansion"
version = "0.0.4"
author = "Lane"
description = "Increases the max recognized rows in placeables.2da from 256 to 2,147,483,648. This is experimental and still in need of thorough testing."

requires = []

conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"