[metadata]
target_versions = ["1C536C3EF2E8BED348B38934B381E3DC427F3EBEE21FADDFBD7524FBB2388D77"]

# KOTOR 2 GOG Aspyr / swkotor2.exe
#
# Original behavior, roughly:
#   Buy confirmation threshold  = max(player_level * 50, 50)
#   Sell confirmation threshold = min(player_level * 50, 250)
#
# Patched behavior:
#   Buy confirmation threshold  = 2500
#   Sell confirmation threshold = 2500
#
# 2500 decimal = 0x000009C4 = C4 09 00 00 little-endian.
#
# To switch from a raw file offset to the virtual address (what you'd see in Ghidra):
# Raw Offset + 0x100000000 - 0x1000 = VA

# Sell path  
# The vanilla code creates a fallback (presetting the R14D register to 250).
# This modification changes that fallbak to 2500.
# 0x10020693d is 0x20793d
[[hooks]]
address = 0x20793F
type = "simple"
original_bytes = [0xfa, 0x00]
replacement_bytes = [0xc4, 0x09]

# And this modification forces the code to use that fallback.
# 0x100206968 is 0x207968
[[hooks]]
address = 0x207968
type = "simple"
original_bytes = [0x77]
replacement_bytes = [0xEB]

# Buy path: 
# Same as the sell path's first step: changing fallback from 50 to 250.
# 0x100207020 is 0x208020
[[hooks]]
address = 0x208022
type = "simple"
original_bytes = [0x32, 0x00]
replacement_bytes = [0xc4, 0x09]

# And forcing the fallback (jumping the alternative calculation).
# 0x100207029 is 0x208029
[[hooks]]
address = 0x208029
type = "simple"
original_bytes = [0x74]
replacement_bytes = [0xeb]
