# Example DETOUR Hook Configuration
# This demonstrates hooking a function with parameter extraction

[[hooks]]
# Memory address to hook (use a disassembler to find this)
address = 0x00401234

# Function name exported from your DLL
function = "MyHookFunction"

# Hook type (detour = DLL-based with wrapper)
type = "detour"

# Original bytes at this address (for verification)
# Use a disassembler or debugger to get these
original_bytes = [
    0x55,              # PUSH EBP
    0x8B, 0xEC,        # MOV EBP, ESP
    0x83, 0xEC, 0x20   # SUB ESP, 0x20
]

# Optional: Extract parameters from registers/stack
[[hooks.parameters]]
source = "eax"
type = "pointer"

[[hooks.parameters]]
source = "[esp+8]"
type = "int"

# Optional: State preservation (defaults to true)
preserve_registers = true
preserve_flags = true

# Optional: Exclude specific registers from restoration
exclude_from_restore = []
