# Example DETOUR Patch Manifest
# This patch demonstrates a DLL-based hook with parameter extraction

[patch]
id = "example-detour-patch"
name = "Example DETOUR Patch"
version = "1.0.0"
author = "Your Name"
description = "An example patch that uses a compiled DLL to hook game code"

[game]
title = "Star Wars: Knights of the Old Republic"
executable = "swkotor.exe"

# Replace this hash with your game version's hash
# Use: kpatchconsole --status <game_exe> to get the hash
[[game.versions]]
name = "4CD"
sha256 = "dbd602d92bfbf2bb8467861b4c3f8d260ce0280e831c923e60c77ba1a5d02e2a"

# Optional: Patches this patch depends on
[dependencies]
# requires = ["base-patch", "another-patch"]

# Optional: Patches this conflicts with
[conflicts]
# conflicts_with = ["incompatible-patch"]
