
# CClientExoAppInternal::IsValidResolution
[[hooks]]
address = 0x005f0c60
type = "simple"
original_bytes =	[
						0x8b, 0x44, 0x24, 0x04,
						0x3d, 0x20, 0x03, 0x00, 0x00
					]		
replacement_bytes = [
						0xB8, 0x01, 0x00, 0x00, 0x00,	# MOV EAX, 0x1
						0xC2, 0x08, 0x00, 0x00			# RET 0x8
					]	

