
# Expand the VM Commands array
[[hooks]]
address = 0x0054c964
type = "simple"

# Allocates space for 1000 commands, instead of 772
original_bytes = [0x68, 0x10, 0x0c, 0x00, 0x00]
replacement_bytes = [0x68, 0xa0, 0x0f, 0x00, 0x00]

[[hooks]]
address = 0x005cd6fb
type = "simple"

# Restore return instruction after the detour
original_bytes = [0x90]
replacement_bytes = [0xc3]


[[hooks]]
address = 0x005cd6f6

function = "InitializeExtensionCommands"
original_bytes = [0xc3, 0x90, 0x90, 0x90, 0x90]

type = "detour"
exclude_from_restore = []

[[hooks.parameters]]
source = "eax"        
type = "pointer" # Commands
