; =================================================
; The KPM Mods Namespace File (9/15/2026) 
; =================================================
; Note: You can insert blank lines between [sections] (but NOT between keys within a section!) and add comment lines starting with semicolon to make it more readable without breaking anything. -------------------------------------------------------------------

[Namespaces]
Namespace1=Default
Namespace2=K1 Expanded Vanilla Options
Namespace3=K1 Max Level Increase
Namespace4=K2 Full Party Select
Namespace5=Script Extender

; ===================================================================
[Default]
IniName=
InfoName=info.rtf
DataPath=Default
Name=(Select a Mod)
Description=Choose a mod from the drop down to begin.

[K1 Expanded Vanilla Options]
IniName=changes.ini
InfoName=info.rtf
DataPath=Expanded Vanilla Options
Name=K1 Expanded Vanilla Options
Description=The attendant mod for the Expanded Vanilla Options patch.

[K1 Max Level Increase]
IniName=changes.ini
InfoName=info.rtf
DataPath=Max Level Increase
Name=K1 Max Level Increase
Description=The attendant mod for the Max Level Increase patch.

[K2 Full Party Select]
IniName=changes.ini
InfoName=info.rtf
DataPath=Full Party Select
Name=K2 Full Party Select
Description=The attendant mod for the Full Party Select patch.

[Script Extender]
IniName=changes.ini
InfoName=info.rtf
DataPath=Script Extender
Name=Script Extender
Description=The attendant mod for the Script Extender patch.


