[patch]
id = "k1widescreenpatch"
name = "Widescreen Patch (beta)"
version = "1.0"
description = "Alone, this widescreen patch provides a vanilla but scaled up version of KOTOR. But it can also be paired with custom GUIs with edits to swkotor.ini. The patch auto detects resolution, but resolution can be forced w/ .ini variables ForceWidth/ForceHeight. REQUIRED: the Stray Bug Fixes patch."
author = "FTD, RaymanGT, J, Vriff"

requires = ["k1-stray-bug-fixes-patch"]

[patch.supported_versions]
kotor1_steam_aspyr_macos = "C1FCB8D37C702849882A17751C63EE0AF7C2B9CBBC3B31B98A5F0EDBC27C6D71"
