[patch]
id = "k1widescreenpatch"
name = "Widescreen Patch (beta)"
version = "0.0.1"
description = "Widescreen patch featuring HUD and menu scaling and re-alignment. Set resolution via Height and Width variables in swkotor.ini. No .gui files required."
author = "J, FTD, Antigravity (Gemini 8)"

[patch.supported_versions]
kotor1_steam_aspyr_macos = "C1FCB8D37C702849882A17751C63EE0AF7C2B9CBBC3B31B98A5F0EDBC27C6D71"
