[patch]
id = "k1widescreenpatch"
name = "Widescreen Patch (beta)"
version = "0.9"
description = "Alone, this widescreen patch provides a scaled-up vanilla version of KOTOR. But it can also be paired with custom GUIs with edits to swkotor.ini. Resolution can optionally be forced but is otherwise auto-detected. REQUIRED: the Stray Bug Fixes patch."
author = "FTD, RaymanGT, J, Vriff"

requires = ["k1-stray-bug-fixes-patch"]

[patch.supported_versions]
kotor1_steam_aspyr_macos = "C1FCB8D37C702849882A17751C63EE0AF7C2B9CBBC3B31B98A5F0EDBC27C6D71"
