[metadata]
target_versions = [
    "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435",
    "761F9466F456A83909036BAEBB5C43167D722387BE66E54617BA20A8C49E9886",
]

[[hooks]]
address = 0x00443820
type = "detour"
function = "InitializeReferencedModelStealth"
original_bytes = [0x64, 0xA1, 0x00, 0x00, 0x00, 0x00]
skip_original_bytes = false
exclude_from_restore = []

[[hooks.parameters]]
source = "ecx"
type = "pointer"

[[hooks.parameters]]
source = "[esp+4]"
type = "pointer"

[[hooks.parameters]]
source = "[esp+0]"
type = "pointer"

[[hooks.parameters]]
source = "const:0x17C"
type = "uint"

[[hooks.parameters]]
source = "const:0x004448C0"
type = "uint"

[[hooks.parameters]]
source = "const:0x00444D90"
type = "uint"

[[hooks]]
address = 0x00449AF0
type = "detour"
function = "EnableReferencedModelStealth"
original_bytes = [0xC6, 0x81, 0x7C, 0x01, 0x00, 0x00, 0x01]
skip_original_bytes = false
exclude_from_restore = []

[[hooks.parameters]]
source = "ecx"
type = "pointer"

[[hooks.parameters]]
source = "const:0x17C"
type = "uint"

[[hooks]]
address = 0x0044B2F0
type = "detour"
function = "CleanupReferencedModelStealth"
original_bytes = [0x6A, 0xFF, 0x68, 0x03, 0x64, 0x71, 0x00]
skip_original_bytes = false
exclude_from_restore = []

[[hooks.parameters]]
source = "ecx"
type = "pointer"

[[hooks]]
address = 0x00449B00
type = "detour"
function = "DisableReferencedModelStealth"
original_bytes = [0xC6, 0x81, 0x7C, 0x01, 0x00, 0x00, 0x00]
skip_original_bytes = false
exclude_from_restore = []

[[hooks.parameters]]
source = "ecx"
type = "pointer"

[[hooks.parameters]]
source = "const:0x17C"
type = "uint"
