// The built-in Linux mapping table, generated by tools/generate-embedded-db.py.

#ifndef CONTROLLER_DB_EMBEDDED_H
#define CONTROLLER_DB_EMBEDDED_H

extern const char* const kEmbeddedLinuxMappings[];
extern const int kEmbeddedLinuxMappingCount;

#endif
