[patch]
id = "anti-crash-prophylactics"
name = "Anti-Crash Prophylactics"
version = "0.0.1"
description = "Some mods can have flaws that cause game-crashing errors (possibly only on certain versions of the game). This patch attempts to add some protection against those crashes."
author = "FTD"

[patch.supported_versions]
kotor1_steam_aspyr_macos = "C1FCB8D37C702849882A17751C63EE0AF7C2B9CBBC3B31B98A5F0EDBC27C6D71"