; =================================================
; Attendant mod of Expanded Vanilla Options
; =================================================
; This document was manually created. Note: You can insert blank lines between [sections] (but NOT between keys within a section!) and add comment lines starting with a semicolon to make this document more readable without breaking anything. 
; -------------------------------------------------------------------

[Settings]
WindowCaption=Expanded Vanilla Options Attendant Mod
BackupFiles=1
ConfirmMessage=N/A
LogLevel=3
InstallerMode=1
PlaintextLog=1
LookupGameFolder=0
SaveProcessedScripts=1

[InstallList]
install_folder0=mod options

[install_folder0]
File0=additional-debug.toml
File1=additional-game.toml
File2=additional-graphics.toml