namespace KPatchCore.Models;

/// <summary>
/// Represents the runtime configuration (patch_config.toml) that the C++ patcher reads
/// This is generated by KPatchCore during installation
/// </summary>
public sealed class PatchConfig
{
    /// <summary>
    /// SHA-256 hash of the target game version
    /// Used by C++ runtime to load the correct address database
    /// </summary>
    public string? TargetVersionSha { get; init; }

    /// <summary>
    /// List of enabled patches with their hooks
    /// </summary>
    public List<EnabledPatch> Patches { get; init; } = new();

    /// <summary>
    /// Represents a single enabled patch in the configuration
    /// </summary>
    public sealed class EnabledPatch
    {
        /// <summary>
        /// Patch identifier (for debugging/logging)
        /// </summary>
        public required string Id { get; init; }

        /// <summary>
        /// Path to patch DLL relative to game directory (e.g., "patches/widescreen-fix.dll")
        /// </summary>
        public required string Dll { get; init; }

        /// <summary>
        /// List of hooks for this patch
        /// </summary>
        public List<Hook> Hooks { get; init; } = new();

        /// <summary>
        /// The value each of the patch's options was installed with, by option id.
        /// Not part of patch_config.toml: recorded in the patch's INI file in the configs
        /// folder, where the patch's own code, scripts and the launcher read what was
        /// chosen. Empty for a patch without options.
        /// </summary>
        public Dictionary<string, string> Options { get; init; } = new();
    }

    /// <summary>
    /// Adds a patch to the configuration
    /// </summary>
    public void AddPatch(string id, string dllPath, IEnumerable<Hook> hooks,
        IReadOnlyDictionary<string, string>? options = null)
    {
        Patches.Add(new EnabledPatch
        {
            Id = id,
            Dll = dllPath,
            Hooks = hooks.ToList(),
            Options = options?.ToDictionary(kv => kv.Key, kv => kv.Value) ?? new()
        });
    }

    /// <summary>
    /// Gets the total number of hooks across all patches
    /// </summary>
    public int TotalHooks => Patches.Sum(p => p.Hooks.Count);

    public override string ToString() =>
        $"{Patches.Count} patches, {TotalHooks} hooks";
}
