[patch]
id = "repeating-blaster-fix"
name = "Repeating Blaster Fix"
version = "0.1.0"
author = "Lane"
description = "Restores the missing Extra Attack that repeating blasters are meant to have"

requires = []
conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"
kotor1_steam_103 = "34E6D971C034222A417995D8E1E8FDD9F8781795C9C289BD86C499A439F34C88"
