; ===============================================
; Intentionally left blank.
; ===============================================
[Settings]
ConfirmMessage=You haven't selected a mod yet! Clicking Ok will not install anything.