[menu]
name = "Additional Game Options"
description = "Vanilla game options that aren't usually accessible in-game."

patch = "expanded-vanilla-options"

[[options]]
name = "Disable Movies"
type = "toggle"
default = 0
ini = "swkotor.ini"
category = "Game Options"
key = "Disable Movies"
function = "AdditionalOptions_GameHandler"
description = "Prevents pre-rendered cinematics from playing"

[[options]]
name = "Camera Acceleration"
type = "text"
default = "500.0"
ini = "swkotor.ini"
category = "Game Options"
key = "Keyboard Camera Acceleration"
function = "AdditionalOptions_GameHandler"
description = "How rapidly camera rotation will speed up when turning it"

[[options]]
name = "Camera Deceleration"
type = "text"
default = "2000.0"
ini = "swkotor.ini"
category = "Game Options"
key = "Keyboard Camera Deceleration"
function = "AdditionalOptions_GameHandler"
description = "How rapidly camera rotation will slow down after releasing control"

[[options]]
name = "Camera DPS"
type = "text"
default = "200.0"
ini = "swkotor.ini"
category = "Game Options"
key = "Keyboard Camera DPS"
function = "AdditionalOptions_GameHandler"
description = "Speed at which the camera rotates"

[[options]]
name = "Tooltip Delay Seconds"
type = "text"
default = "1.0"
ini = "swkotor.ini"
category = "Game Options"
key = "TooltipDelay Sec"
function = "AdditionalOptions_GameHandler"
description = "Number of seconds after hovering a main-interface control before a tool-tip appears (requires tooltips to be enabled)"

[[options]]
name = "EnableCheats"
type = "toggle"
default = 0
ini = "swkotor.ini"
category = "Game Options"
key = "EnableCheats"
function = "AdditionalOptions_GameHandler"
description = "Allows accessing the cheat menu with the '`' key"
