[menu]
name = "Additional Graphics Options"
description = "Vanilla graphics options that aren't usually accessible in-game."

patch = "expanded-vanilla-options"

[[options]]
name = "Emitters"
type = "toggle"
default = 1
ini = "swkotor.ini"
category = "Graphics Options"
key = "Emitters"
function = "AdditionalOptions_GraphicsHandler"
description = "Enables to the Emitter bucket rendering. Makes a subtle difference in some areas."

[[options]]
name = "Full Screen"
type = "toggle"
default = 1
ini = "swkotor.ini"
category = "Graphics Options"
key = "FullScreen"
function = "AdditionalOptions_GraphicsHandler"
description = "Will toggle the current full screen state."

[[options]]
name = "Allow Windowed Mode"
type = "toggle"
default = 1
ini = "swkotor.ini"
category = "Graphics Options"
key = "AllowWindowedMode"
function = "AdditionalOptions_GraphicsHandler"
description = "If set, then disabling Full Screen will allow the game to switch to Windowed Mode."

[[options]]
name = "Disable Vertex Buffer Objects"
type = "toggle"
default = 1
ini = "swkotor.ini"
category = "Graphics Options"
key = "Disable Vertex Buffer Objects"
function = "AdditionalOptions_GraphicsHandler"
description = "VBO handling can cause crashing on some hardware"

[[options]]
name = "Disable Write-Only VBO"
type = "toggle"
default = 0
ini = "swkotor.ini"
category = "Graphics Options"
key = "Disable Write-Only VBO"
function = "AdditionalOptions_GraphicsHandler"
description = "Write-Only VBO handling can cause crashing on some hardware"

[[options]]
name = "Disable GUI"
type = "toggle"
default = 0
ini = "additional-options.ini"
category = "Graphics Options"
key = "DisableGUI"
function = "AdditionalOptions_GraphicsHandler"
description = "Turns off GUI rendering. NOTE: This may make using menus quite difficult. If you are stuck, disable this from additional-options.ini"

[[options]]
name = "Render Level"
type = "list"
choices = ["0", "1", "2"]
default = "2"
ini = "additional-options.ini"
category = "Graphics Options"
key = "RenderLevel"
function = "AdditionalOptions_GraphicsHandler"
description = "A render level of 2 will attempt to render with all features (as made available by other graphics settings). Lower values will bypass certain aspects of texture bump-mapping, and shininess."

[[options]]
name = "Do 3D Gui"
type = "toggle"
default = 1
ini = "additional-options.ini"
category = "Graphics Options"
key = "Do3dGui"
function = "AdditionalOptions_GraphicsHandler"
description = "Determines whether certain 3D GUI elements (such as the player model on the character sheet) will render."

[[options]]
name = "Visibility Graph"
type = "toggle"
default = 1
ini = "additional-options.ini"
category = "Graphics Options"
key = "VisibilityGraph"
function = "AdditionalOptions_GraphicsHandler"
description = "Determines if rooms consider non visible (according to the current module's `.vis` file) will be culled or not."

[[options]]
name = "Beams"
type = "toggle"
default = 1
ini = "additional-options.ini"
category = "Graphics Options"
key = "Beams"
function = "AdditionalOptions_GraphicsHandler"
description = "Determines whether static mesh beams will render. Makes a subtle difference in some areas."

[[options]]
name = "Do Grass Wind"
type = "toggle"
default = 1
ini = "additional-options.ini"
category = "Graphics Options"
key = "DoGrassWind"
function = "AdditionalOptions_GraphicsHandler"
description = "Determines whether grass will sway in the wind. Requires grass be enabled."