# HUD minimap map draw-size fix.
# Allows for higher resolution map textures.

[[hooks]]
address = 0x0068ABF8
type = "replace"
original_bytes = [0x8B, 0x96, 0x00, 0x5E, 0x00, 0x00]
replacement_bytes = [
    # mov dword ptr [esp+0x30], 512
    0xC7, 0x44, 0x24, 0x30, 0x00, 0x02, 0x00, 0x00,
    # mov dword ptr [esp+0x34], 256
    0xC7, 0x44, 0x24, 0x34, 0x00, 0x01, 0x00, 0x00,
    # original instruction: mov edx, [esi+0x5E00]
    0x8B, 0x96, 0x00, 0x5E, 0x00, 0x00
]
