[patch]
id = "alt-tab-patch-v1"
name = "Alt Tab Patch"
version = "1.6.1"
author = "J"
description = "Returns cleanly from Alt-Tab in exclusive fullscreen while preserving display resolution."

requires = []

conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"
kotor1_cdcrack_103 = "761F9466F456A83909036BAEBB5C43167D722387BE66E54617BA20A8C49E9886"
