; =================================================
; Attendant mod of Full Party Select
; =================================================
; This document was manually created. Note: You can insert blank lines between [sections] (but NOT between keys within a section!) and add comment lines starting with a semicolon to make this document more readable without breaking anything. -------------------------------------------------------------------

[Settings]
WindowCaption=Full Party Select Attendant Mod
BackupFiles=1
ConfirmMessage=N/A
LogLevel=3
InstallerMode=1
PlaintextLog=1
LookupGameFolder=0
LookupGameNumber=2
SaveProcessedScripts=1

[InstallList]
Folder0=override

[Folder0]
File0=partyselect_p.gui
