#!/usr/bin/env python3
"""Compile the Linux rows of a SDL_GameControllerDB snapshot into the module.

Reads the snapshot beside this script, writes ControllerDbEmbedded.cpp into the
patch root where create-patch.py finds it. Refresh the snapshot from
https://github.com/mdqinc/SDL_GameControllerDB, rerun this, rebuild.

Linux rows only: SDL_GameControllerAddMapping does no platform filtering, so
another platform's row could shadow the Linux row for the same pad. The first
field must be 32 hex digits, which rejects upstream's "xinput,..." row, whose
first field is a Windows XInput token rather than a GUID.
"""

import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
SOURCE = HERE / "gamecontrollerdb.txt"
OUTPUT = HERE.parent / "ControllerDbEmbedded.cpp"
PLATFORM_TAG = "platform:Linux,"

HEADER = """// Generated by tools/generate-embedded-db.py. Do not edit.
//
// Linux rows of a SDL_GameControllerDB snapshot, compiled in so the patch works
// with no loose files. An external gamecontrollerdb.txt beside the game binary
// takes precedence; see ControllerDB.cpp.

#include "ControllerDbEmbedded.h"

const char* const kEmbeddedLinuxMappings[] = {"""

FOOTER = """};

const int kEmbeddedLinuxMappingCount =
    static_cast<int>(sizeof(kEmbeddedLinuxMappings) / sizeof(kEmbeddedLinuxMappings[0]));
"""


def has_guid_prefix(row):
    return (len(row) > 32 and row[32] == ","
            and all(c in "0123456789abcdefABCDEF" for c in row[:32]))


def main():
    if not SOURCE.is_file():
        sys.exit("missing %s" % SOURCE)

    rows = {}
    for line in SOURCE.read_text(encoding="utf-8", errors="replace").splitlines():
        row = line.strip()
        if not row or row.startswith("#"):
            continue
        if PLATFORM_TAG not in row or not has_guid_prefix(row):
            continue
        rows.setdefault(row[:32].lower(), row)

    body = ['    "%s",' % rows[g].replace("\\", "\\\\").replace('"', '\\"')
            for g in sorted(rows)]
    OUTPUT.write_text("\n".join([HEADER, *body, FOOTER]), encoding="ascii")
    print("wrote %s with %d Linux mappings" % (OUTPUT.name, len(rows)))


if __name__ == "__main__":
    main()
