[[hooks]]
address = 0x005cb41c
function = "EnableAurPostString_Hook"
original_bytes = [
	0x8d, 0x4c, 0x24, 0x0c,						   # LEA ECX, [ESP+0xc]
	0xc7, 0x44, 0x24, 0x1c, 0xff, 0xff, 0xff, 0xff # MOV dword ptr [ESP+0x1c], -1
]
type = "detour"
skip_original_bytes=false
exclude_from_restore = []

[[hooks.parameters]]
source = "eax"        # string from EAX register
type = "pointer"

[[hooks.parameters]]
source = "esp+0"      # x from [ESP]
type = "pointer"

[[hooks.parameters]]
source = "esp+4"      # y from [ESP+4]
type = "pointer"

[[hooks.parameters]]
source = "esp+8"      # life from [ESP+8]
type = "pointer"